{{- if .Values.webHooksEnabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | indent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | indent 4 }}
spec:
  dnsNames:
    - {{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-selfsigned-issuer
  secretName: {{ .Release.Name }}-cert
{{- end }}