{{- if .Values.webHooksEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | indent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    {{- include "operator.labels" . | indent 4 }}
{{- end }}