image: ghcr.io/nibiruchain/cosmopilot
nodeUtilsImage: ghcr.io/nibiruchain/node-utils:2.6.0
cosmoGuardImage: ghcr.io/nibiruchain/cosmoguard:2.3.0
replicas: 1
serviceMonitorEnabled: true
imagePullSecrets: []
workerCount: 1
workerName: ""
webHooksEnabled: true
nodeSelector: {}
debugMode: false
probesEnabled: true
disruptionChecksEnabled: true

nodesPodPriority: 950
validatorPodPriority: 1050
defaultPriority: 0