{{- $existingDefaultClass := lookup "scheduling.k8s.io/v1" "PriorityClass" "" (printf "%s-default" .Release.Name) }}
{{- if $existingDefaultClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-default
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "cosmopilot.labels" . | indent 4 }}
value: {{ .Values.defaultPriority }}
globalDefault: false
description: "Delete default priority class before upgrading"
{{- end }}
---
# Always create the PriorityClass after checking/deleting existing ones
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-default
  labels:
    {{- include "cosmopilot.labels" . | indent 4 }}
value: {{ .Values.defaultPriority }}
globalDefault: false
description: "CosmoPilot default priority class for background jobs and normal workloads"
---
{{- $existingNodesClass := lookup "scheduling.k8s.io/v1" "PriorityClass" "" (printf "%s-nodes" .Release.Name) }}
{{- if $existingNodesClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-nodes
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "cosmopilot.labels" . | indent 4 }}
value: {{ .Values.nodesPodPriority }}
globalDefault: false
description: "Delete nodes priority class before upgrading"
{{- end }}
---
# Always create the PriorityClass after checking/deleting existing ones
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-nodes
  labels:
    {{- include "cosmopilot.labels" . | indent 4 }}
value: {{ .Values.nodesPodPriority }}
globalDefault: false
description: "CosmoPilot priority class for nodes"
---
{{- $existingValidatorsClass := lookup "scheduling.k8s.io/v1" "PriorityClass" "" (printf "%s-validators" .Release.Name) }}
{{- if $existingValidatorsClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-validators
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "cosmopilot.labels" . | indent 4 }}
value: {{ .Values.validatorPodPriority }}
globalDefault: false
description: "Delete validator priority class before upgrading"
{{- end }}
---
# Always create the PriorityClass after checking/deleting existing ones
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-validators
  labels:
    {{- include "cosmopilot.labels" . | indent 4 }}
value: {{ .Values.validatorPodPriority }}
globalDefault: false
description: "CosmoPilot priority class for validator nodes"