# permissions for end users to view chainnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chainnode-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nibiru-operator
    app.kubernetes.io/part-of: nibiru-operator
    app.kubernetes.io/managed-by: kustomize
  name: chainnode-viewer-role
rules:
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodes/status
  verbs:
  - get
