image: ghcr.io/nibiruchain/nibiru-operator
nodeUtilsImage: ghcr.io/nibiruchain/node-utils
replicas: 1
serviceMonitorEnabled: true
imagePullSecrets: []
workerCount: 1
workerName: ""
webHooksEnabled: true
nodeSelector: {}
debugMode: false