---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodes
  - chainnodesets
  - ingresses
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodes
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodesets/finalizers
  verbs:
  - update
- apiGroups:
  - apps.k8s.nibiru.org
  resources:
  - chainnodesets/status
  verbs:
  - get
  - patch
  - update
