apiVersion: apps.k8s.nibiru.org/v1
kind: ChainNodeSet
metadata:
  name: cosmos-devnet
spec:
  app:
    image: ghcr.io/akash-network/cosmos-omnibus
    version: v0.4.20-cosmoshub-v17.3.0
    app: gaiad

  validator:
    info:
      moniker: nibiru-0
      website: https://nibiru.fi

    config:
      volumes:
        - name: wasm
          size: 1Gi
          path: /home/app/wasm
          deleteWithNode: true
      override:
        app.toml:
          minimum-gas-prices: 0.025uatom
          mempool:
            max-txs: 100000
        config.toml:
          mempool:
            size: 100000
            cache_size: 200000

    init:
      chainID: cosmos-devnet-0
      assets: ["1000000000000000000uatom"]
      stakeAmount: 100000000uatom
      minSelfDelegation: ""
      accountPrefix: cosmos
      valPrefix: cosmosvaloper
      unbondingTime: 60s
      votingPeriod: 60s
      additionalInitCommands:
        # Use uATOM as default denom
        - image: busybox
          command: [ "sh", "-c" ]
          args:
            - > 
              sed -i 's/stake/uatom/g' /home/app/config/genesis.json;
              sed -i 's/uatomrs/stakers/g' /home/app/config/genesis.json;
              sed -i 's/uatomd/staked/g' /home/app/config/genesis.json;

  nodes:
    - name: fullnodes
      instances: 1

      config:
        override:
          app.toml:
            minimum-gas-prices: 0.025uatom
            pruning: custom
            pruning-keep-recent: "100"
            pruning-interval: "10"
