apiVersion: apps.k8s.nibiru.org/v1
kind: ChainNode
metadata:
  name: axelar-lisbon-3
spec:
  app:
    image: axelarnet/axelar-core
    version: v0.33.0
    app: axelard

  genesis:
    url: https://raw.githubusercontent.com/axelarnetwork/axelarate-community/main/resources/testnet/genesis.json

  peers:
    - id: a005b8923888007eb5cf9ed8c8120ed956bc31f7
      address: k8s-testnet-axelarco-c0dd71f944-b4c8da2f814e7b8f.elb.us-east-2.amazonaws.com

    - id: c6fc21118312ff69f93124e9db70067a610db9ae
      address: public-seed.testnet.axelar.lunanova.tech

  config:
    override:
      app.toml:
        minimum-gas-prices: 0.007uaxl