apiVersion: apps.k8s.nibiru.org/v1
kind: ChainNode
metadata:
  name: nibiru-validator-1
spec:
  app:
    image: ghcr.io/nibiruchain/nibiru
    version: 0.21.9
    app: nibid

  genesis:
    fromNodeRPC:
      hostname: nibiru-validator

  stateSyncRestore: true

  validator:
    info:
      moniker: nibiru-join
      website: https://nibiru.fi

    createValidator:
      stakeAmount: 100000000unibi
      gasPrices: 0.025unibi

  config:
    sidecars:
      - name: pricefeeder
        image: ghcr.io/nibiruchain/pricefeeder:0.21.6
        env:
          - name: FEEDER_MNEMONIC
            valueFrom:
              secretKeyRef:
                name: nibiru-validator-1-account
                key: mnemonic
          - name: CHAIN_ID
            value: nibiru-devnet-0
          - name: GRPC_ENDPOINT
            value: localhost:9090
          - name: WEBSOCKET_ENDPOINT
            value: ws://localhost:26657/websocket
          - name: EXCHANGE_SYMBOLS_MAP
            value: '{"bitfinex": {"ubtc:unusd": "tBTCUSD","ubtc:uusd": "tBTCUSD","ueth:unusd": "tETHUSD","ueth:uusd": "tETHUSD","uusdc:uusd": "tUDCUSD","uusdc:unusd": "tUDCUSD",},"coingecko": {"ubtc:uusd": "bitcoin","ubtc:unusd": "bitcoin","ueth:uusd": "ethereum","ueth:unusd": "ethereum","uusdt:uusd": "tether","uusdt:unusd": "tether","uusdc:uusd": "usd-coin","uusdc:unusd": "usd-coin","uatom:uusd": "cosmos","uatom:unusd": "cosmos","ubnb:uusd": "binancecoin","ubnb:unusd": "binancecoin","uavax:uusd": "avalanche-2","uavax:unusd": "avalanche-2","usol:uusd": "solana","usol:unusd": "solana","uada:uusd": "cardano","uada:unusd": "cardano"}}'

    override:
      app.toml:
        minimum-gas-prices: 0.025unibi