apiVersion: apps.k8s.nibiru.org/v1
kind: ChainNode
metadata:
  name: nibiru-validator
spec:
  app:
    image: ghcr.io/nibiruchain/nibiru
    version: 0.21.9
    app: nibid

  validator:
    info:
      moniker: nibiru
      website: https://nibiru.fi
    init:
      chainID: nibiru-devnet-0
      assets: [ "1000000000000000unibi" ]
      stakeAmount: 100000000unibi
      unbondingTime: 86400s
      votingPeriod: 30s
      additionalInitCommands:
        - image: ghcr.io/nibiruchain/node-tools
          command: [ "sh" , "-c" ]
          args:
            - >
              curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd" -o /temp/coingecko.json;
              jq '.bitcoin.usd' /temp/coingecko.json > /temp/bitcoin;
              jq '.ethereum.usd' /temp/coingecko.json > /temp/ethereum;
              jq '.app_state.oracle.params.min_voters = "1"' /home/app/config/genesis.json | sponge /home/app/config/genesis.json;

        - command: [ "sh" , "-c" ]
          args:
            - >
              nibid genesis add-genesis-perp-market
              --pair=ubtc:unusd
              --sqrt-depth=40000000000000
              --price-multiplier=$(cat /temp/bitcoin)
              --max-leverage=10
              --mmr=0.05
              --home=/home/app

        - command: [ "sh" , "-c" ]
          args:
            - >
              nibid genesis add-genesis-perp-market
              --pair=ueth:unusd
              --sqrt-depth=40000000000000
              --price-multiplier=$(cat /temp/ethereum)
              --max-leverage=15
              --mmr=0.05
              --home=/home/app

  config:
    stateSync:
      snapshotInterval: 100
    override:
      app.toml:
        minimum-gas-prices: 0.025unibi