name: Build node-tools image

on:
  push:
    tags:
      - "node-tools/*"

jobs:
  node-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        uses: nowsprinting/check-version-format-action@v3
        with:
          prefix: node-tools/v

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.tools
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nibiruchain/node-tools:latest,ghcr.io/nibiruchain/node-tools:${{ steps.get_version.outputs.full_without_prefix }}