name: Build vault-renewer image

on:
  push:
    tags:
      - "vault-renewer/*"

jobs:
  vault-renewer:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        uses: nowsprinting/check-version-format-action@v3
        with:
          prefix: vault-renewer/v

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.vaultRenewer
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nibiruchain/vault-token-renewer:latest, ghcr.io/nibiruchain/vault-token-renewer:${{ steps.get_version.outputs.full_without_prefix }}
